/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * This structure contains parameters for Call::vidSetStream()
 */
public class CallVidSetStreamParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallVidSetStreamParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallVidSetStreamParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CallVidSetStreamParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_CallVidSetStreamParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Specify the media stream index. This can be set to -1 to denote<br>
   * the default video stream in the call, which is the first active<br>
   * video stream or any first video stream if none is active.<br>
   * <br>
   * This field is valid for all video stream operations, except<br>
   * PJSUA_CALL_VID_STRM_ADD.<br>
   * <br>
   * Default: -1 (first active video stream, or any first video stream<br>
   *              if none is active)
   */
  public void setMedIdx(int value) {
    pjsua2JNI.CallVidSetStreamParam_medIdx_set(swigCPtr, this, value);
  }

  /**
   * Specify the media stream index. This can be set to -1 to denote<br>
   * the default video stream in the call, which is the first active<br>
   * video stream or any first video stream if none is active.<br>
   * <br>
   * This field is valid for all video stream operations, except<br>
   * PJSUA_CALL_VID_STRM_ADD.<br>
   * <br>
   * Default: -1 (first active video stream, or any first video stream<br>
   *              if none is active)
   */
  public int getMedIdx() {
    return pjsua2JNI.CallVidSetStreamParam_medIdx_get(swigCPtr, this);
  }

  /**
   * Specify the media stream direction.<br>
   * <br>
   * This field is valid for the following video stream operations:<br>
   * PJSUA_CALL_VID_STRM_ADD and PJSUA_CALL_VID_STRM_CHANGE_DIR.<br>
   * <br>
   * Default: PJMEDIA_DIR_ENCODING_DECODING
   */
  public void setDir(int value) {
    pjsua2JNI.CallVidSetStreamParam_dir_set(swigCPtr, this, value);
  }

  /**
   * Specify the media stream direction.<br>
   * <br>
   * This field is valid for the following video stream operations:<br>
   * PJSUA_CALL_VID_STRM_ADD and PJSUA_CALL_VID_STRM_CHANGE_DIR.<br>
   * <br>
   * Default: PJMEDIA_DIR_ENCODING_DECODING
   */
  public int getDir() {
    return pjsua2JNI.CallVidSetStreamParam_dir_get(swigCPtr, this);
  }

  /**
   * Specify the video capture device ID. This can be set to<br>
   * PJMEDIA_VID_DEFAULT_CAPTURE_DEV to specify the default capture<br>
   * device as configured in the account.<br>
   * <br>
   * This field is valid for the following video stream operations:<br>
   * PJSUA_CALL_VID_STRM_ADD and PJSUA_CALL_VID_STRM_CHANGE_CAP_DEV.<br>
   * <br>
   * Default: PJMEDIA_VID_DEFAULT_CAPTURE_DEV.
   */
  public void setCapDev(int value) {
    pjsua2JNI.CallVidSetStreamParam_capDev_set(swigCPtr, this, value);
  }

  /**
   * Specify the video capture device ID. This can be set to<br>
   * PJMEDIA_VID_DEFAULT_CAPTURE_DEV to specify the default capture<br>
   * device as configured in the account.<br>
   * <br>
   * This field is valid for the following video stream operations:<br>
   * PJSUA_CALL_VID_STRM_ADD and PJSUA_CALL_VID_STRM_CHANGE_CAP_DEV.<br>
   * <br>
   * Default: PJMEDIA_VID_DEFAULT_CAPTURE_DEV.
   */
  public int getCapDev() {
    return pjsua2JNI.CallVidSetStreamParam_capDev_get(swigCPtr, this);
  }

  /**
   * Default constructor
   */
  public CallVidSetStreamParam() {
    this(pjsua2JNI.new_CallVidSetStreamParam(), true);
  }

}
