/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * This structure contains parameters for Call::sendRequest()
 */
public class CallSendRequestParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallSendRequestParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallSendRequestParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CallSendRequestParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_CallSendRequestParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * SIP method of the request.
   */
  public void setMethod(String value) {
    pjsua2JNI.CallSendRequestParam_method_set(swigCPtr, this, value);
  }

  /**
   * SIP method of the request.
   */
  public String getMethod() {
    return pjsua2JNI.CallSendRequestParam_method_get(swigCPtr, this);
  }

  /**
   * Message body and/or list of headers etc to be included in<br>
   * outgoing request.
   */
  public void setTxOption(SipTxOption value) {
    pjsua2JNI.CallSendRequestParam_txOption_set(swigCPtr, this, SipTxOption.getCPtr(value), value);
  }

  /**
   * Message body and/or list of headers etc to be included in<br>
   * outgoing request.
   */
  public SipTxOption getTxOption() {
    long cPtr = pjsua2JNI.CallSendRequestParam_txOption_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SipTxOption(cPtr, false);
  }

  /**
   * Default constructor initializes with zero/empty values.
   */
  public CallSendRequestParam() {
    this(pjsua2JNI.new_CallSendRequestParam(), true);
  }

}
