/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Call information. Application can query the call information<br>
 * by calling Call::getInfo().
 */
public class CallInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CallInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_CallInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Call identification.
   */
  public void setId(int value) {
    pjsua2JNI.CallInfo_id_set(swigCPtr, this, value);
  }

  /**
   * Call identification.
   */
  public int getId() {
    return pjsua2JNI.CallInfo_id_get(swigCPtr, this);
  }

  /**
   * Initial call role (UAC == caller)
   */
  public void setRole(int value) {
    pjsua2JNI.CallInfo_role_set(swigCPtr, this, value);
  }

  /**
   * Initial call role (UAC == caller)
   */
  public int getRole() {
    return pjsua2JNI.CallInfo_role_get(swigCPtr, this);
  }

  /**
   * The account ID where this call belongs.
   */
  public void setAccId(int value) {
    pjsua2JNI.CallInfo_accId_set(swigCPtr, this, value);
  }

  /**
   * The account ID where this call belongs.
   */
  public int getAccId() {
    return pjsua2JNI.CallInfo_accId_get(swigCPtr, this);
  }

  /**
   * Local URI
   */
  public void setLocalUri(String value) {
    pjsua2JNI.CallInfo_localUri_set(swigCPtr, this, value);
  }

  /**
   * Local URI
   */
  public String getLocalUri() {
    return pjsua2JNI.CallInfo_localUri_get(swigCPtr, this);
  }

  /**
   * Local Contact
   */
  public void setLocalContact(String value) {
    pjsua2JNI.CallInfo_localContact_set(swigCPtr, this, value);
  }

  /**
   * Local Contact
   */
  public String getLocalContact() {
    return pjsua2JNI.CallInfo_localContact_get(swigCPtr, this);
  }

  /**
   * Remote URI
   */
  public void setRemoteUri(String value) {
    pjsua2JNI.CallInfo_remoteUri_set(swigCPtr, this, value);
  }

  /**
   * Remote URI
   */
  public String getRemoteUri() {
    return pjsua2JNI.CallInfo_remoteUri_get(swigCPtr, this);
  }

  /**
   * Remote contact
   */
  public void setRemoteContact(String value) {
    pjsua2JNI.CallInfo_remoteContact_set(swigCPtr, this, value);
  }

  /**
   * Remote contact
   */
  public String getRemoteContact() {
    return pjsua2JNI.CallInfo_remoteContact_get(swigCPtr, this);
  }

  /**
   * Dialog Call-ID string.
   */
  public void setCallIdString(String value) {
    pjsua2JNI.CallInfo_callIdString_set(swigCPtr, this, value);
  }

  /**
   * Dialog Call-ID string.
   */
  public String getCallIdString() {
    return pjsua2JNI.CallInfo_callIdString_get(swigCPtr, this);
  }

  /**
   * Call setting
   */
  public void setSetting(CallSetting value) {
    pjsua2JNI.CallInfo_setting_set(swigCPtr, this, CallSetting.getCPtr(value), value);
  }

  /**
   * Call setting
   */
  public CallSetting getSetting() {
    long cPtr = pjsua2JNI.CallInfo_setting_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CallSetting(cPtr, false);
  }

  /**
   * Call state
   */
  public void setState(int value) {
    pjsua2JNI.CallInfo_state_set(swigCPtr, this, value);
  }

  /**
   * Call state
   */
  public int getState() {
    return pjsua2JNI.CallInfo_state_get(swigCPtr, this);
  }

  /**
   * Text describing the state
   */
  public void setStateText(String value) {
    pjsua2JNI.CallInfo_stateText_set(swigCPtr, this, value);
  }

  /**
   * Text describing the state
   */
  public String getStateText() {
    return pjsua2JNI.CallInfo_stateText_get(swigCPtr, this);
  }

  /**
   * Last status code heard, which can be used as cause code
   */
  public void setLastStatusCode(int value) {
    pjsua2JNI.CallInfo_lastStatusCode_set(swigCPtr, this, value);
  }

  /**
   * Last status code heard, which can be used as cause code
   */
  public int getLastStatusCode() {
    return pjsua2JNI.CallInfo_lastStatusCode_get(swigCPtr, this);
  }

  /**
   * The reason phrase describing the last status.
   */
  public void setLastReason(String value) {
    pjsua2JNI.CallInfo_lastReason_set(swigCPtr, this, value);
  }

  /**
   * The reason phrase describing the last status.
   */
  public String getLastReason() {
    return pjsua2JNI.CallInfo_lastReason_get(swigCPtr, this);
  }

  /**
   * Array of active media information.
   */
  public void setMedia(CallMediaInfoVector value) {
    pjsua2JNI.CallInfo_media_set(swigCPtr, this, CallMediaInfoVector.getCPtr(value), value);
  }

  /**
   * Array of active media information.
   */
  public CallMediaInfoVector getMedia() {
    long cPtr = pjsua2JNI.CallInfo_media_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CallMediaInfoVector(cPtr, false);
  }

  /**
   * Array of provisional media information. This contains the media info<br>
   * in the provisioning state, that is when the media session is being<br>
   * created/updated (SDP offer/answer is on progress).
   */
  public void setProvMedia(CallMediaInfoVector value) {
    pjsua2JNI.CallInfo_provMedia_set(swigCPtr, this, CallMediaInfoVector.getCPtr(value), value);
  }

  /**
   * Array of provisional media information. This contains the media info<br>
   * in the provisioning state, that is when the media session is being<br>
   * created/updated (SDP offer/answer is on progress).
   */
  public CallMediaInfoVector getProvMedia() {
    long cPtr = pjsua2JNI.CallInfo_provMedia_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CallMediaInfoVector(cPtr, false);
  }

  /**
   * Up-to-date call connected duration (zero when call is not<br>
   * established)
   */
  public void setConnectDuration(TimeVal value) {
    pjsua2JNI.CallInfo_connectDuration_set(swigCPtr, this, TimeVal.getCPtr(value), value);
  }

  /**
   * Up-to-date call connected duration (zero when call is not<br>
   * established)
   */
  public TimeVal getConnectDuration() {
    long cPtr = pjsua2JNI.CallInfo_connectDuration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeVal(cPtr, false);
  }

  /**
   * Total call duration, including set-up time
   */
  public void setTotalDuration(TimeVal value) {
    pjsua2JNI.CallInfo_totalDuration_set(swigCPtr, this, TimeVal.getCPtr(value), value);
  }

  /**
   * Total call duration, including set-up time
   */
  public TimeVal getTotalDuration() {
    long cPtr = pjsua2JNI.CallInfo_totalDuration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimeVal(cPtr, false);
  }

  /**
   * Flag if remote was SDP offerer
   */
  public void setRemOfferer(boolean value) {
    pjsua2JNI.CallInfo_remOfferer_set(swigCPtr, this, value);
  }

  /**
   * Flag if remote was SDP offerer
   */
  public boolean getRemOfferer() {
    return pjsua2JNI.CallInfo_remOfferer_get(swigCPtr, this);
  }

  /**
   * Number of audio streams offered by remote
   */
  public void setRemAudioCount(long value) {
    pjsua2JNI.CallInfo_remAudioCount_set(swigCPtr, this, value);
  }

  /**
   * Number of audio streams offered by remote
   */
  public long getRemAudioCount() {
    return pjsua2JNI.CallInfo_remAudioCount_get(swigCPtr, this);
  }

  /**
   * Number of video streams offered by remote
   */
  public void setRemVideoCount(long value) {
    pjsua2JNI.CallInfo_remVideoCount_set(swigCPtr, this, value);
  }

  /**
   * Number of video streams offered by remote
   */
  public long getRemVideoCount() {
    return pjsua2JNI.CallInfo_remVideoCount_get(swigCPtr, this);
  }

  /**
   * Number of text streams offered by remote
   */
  public void setRemTextCount(long value) {
    pjsua2JNI.CallInfo_remTextCount_set(swigCPtr, this, value);
  }

  /**
   * Number of text streams offered by remote
   */
  public long getRemTextCount() {
    return pjsua2JNI.CallInfo_remTextCount_get(swigCPtr, this);
  }

  /**
   * Default constructor
   */
  public CallInfo() {
    this(pjsua2JNI.new_CallInfo(), true);
  }

}
