/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Logging configuration, which can be (optionally) specified when calling<br>
 * Lib::init().
 */
public class LogConfig extends PersistentObject {
  private transient long swigCPtr;

  protected LogConfig(long cPtr, boolean cMemoryOwn) {
    super(pjsua2JNI.LogConfig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LogConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_LogConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   *  Log incoming and outgoing SIP message? Yes!  
   */
  public void setMsgLogging(long value) {
    pjsua2JNI.LogConfig_msgLogging_set(swigCPtr, this, value);
  }

  /**
   *  Log incoming and outgoing SIP message? Yes!  
   */
  public long getMsgLogging() {
    return pjsua2JNI.LogConfig_msgLogging_get(swigCPtr, this);
  }

  /**
   *  Input verbosity level. Value 5 is reasonable. 
   */
  public void setLevel(long value) {
    pjsua2JNI.LogConfig_level_set(swigCPtr, this, value);
  }

  /**
   *  Input verbosity level. Value 5 is reasonable. 
   */
  public long getLevel() {
    return pjsua2JNI.LogConfig_level_get(swigCPtr, this);
  }

  /**
   *  Verbosity level for console. Value 4 is reasonable. 
   */
  public void setConsoleLevel(long value) {
    pjsua2JNI.LogConfig_consoleLevel_set(swigCPtr, this, value);
  }

  /**
   *  Verbosity level for console. Value 4 is reasonable. 
   */
  public long getConsoleLevel() {
    return pjsua2JNI.LogConfig_consoleLevel_get(swigCPtr, this);
  }

  /**
   *  Log decoration. 
   */
  public void setDecor(long value) {
    pjsua2JNI.LogConfig_decor_set(swigCPtr, this, value);
  }

  /**
   *  Log decoration. 
   */
  public long getDecor() {
    return pjsua2JNI.LogConfig_decor_get(swigCPtr, this);
  }

  /**
   *  Optional log filename if app wishes the library to write to log file.
   */
  public void setFilename(String value) {
    pjsua2JNI.LogConfig_filename_set(swigCPtr, this, value);
  }

  /**
   *  Optional log filename if app wishes the library to write to log file.
   */
  public String getFilename() {
    return pjsua2JNI.LogConfig_filename_get(swigCPtr, this);
  }

  /**
   * Additional flags to be given to pj_file_open() when opening<br>
   * the log file. By default, the flag is PJ_O_WRONLY. Application<br>
   * may set PJ_O_APPEND here so that logs are appended to existing<br>
   * file instead of overwriting it.<br>
   * <br>
   * Default is 0.
   */
  public void setFileFlags(long value) {
    pjsua2JNI.LogConfig_fileFlags_set(swigCPtr, this, value);
  }

  /**
   * Additional flags to be given to pj_file_open() when opening<br>
   * the log file. By default, the flag is PJ_O_WRONLY. Application<br>
   * may set PJ_O_APPEND here so that logs are appended to existing<br>
   * file instead of overwriting it.<br>
   * <br>
   * Default is 0.
   */
  public long getFileFlags() {
    return pjsua2JNI.LogConfig_fileFlags_get(swigCPtr, this);
  }

  /**
   * Custom log writer, if required. This instance will be destroyed<br>
   * by the endpoint when the endpoint is destroyed.
   */
  public void setWriter(LogWriter value) {
    pjsua2JNI.LogConfig_writer_set(swigCPtr, this, LogWriter.getCPtr(value), value);
  }

  /**
   * Custom log writer, if required. This instance will be destroyed<br>
   * by the endpoint when the endpoint is destroyed.
   */
  public LogWriter getWriter() {
    long cPtr = pjsua2JNI.LogConfig_writer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LogWriter(cPtr, false);
  }

  /**
   *  Default constructor initialises with default values 
   */
  public LogConfig() {
    this(pjsua2JNI.new_LogConfig(), true);
  }

  /**
   * Read this object from a container.<br>
   * <br>
   * @param node              Container to write values from.
   */
  public void readObject(ContainerNode node) throws java.lang.Exception {
    pjsua2JNI.LogConfig_readObject(swigCPtr, this, ContainerNode.getCPtr(node), node);
  }

  /**
   * Write this object to a container.<br>
   * <br>
   * @param node              Container to write values to.
   */
  public void writeObject(ContainerNode node) throws java.lang.Exception {
    pjsua2JNI.LogConfig_writeObject(swigCPtr, this, ContainerNode.getCPtr(node), node);
  }

}
