/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 *  Parameter of Endpoint::onAudioMediaOpCompleted() callback.
 */
public class OnAudioMediaOpCompletedParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnAudioMediaOpCompletedParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnAudioMediaOpCompletedParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OnAudioMediaOpCompletedParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnAudioMediaOpCompletedParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * The operation type.
   */
  public void setOpType(int value) {
    pjsua2JNI.OnAudioMediaOpCompletedParam_opType_set(swigCPtr, this, value);
  }

  /**
   * The operation type.
   */
  public int getOpType() {
    return pjsua2JNI.OnAudioMediaOpCompletedParam_opType_get(swigCPtr, this);
  }

  /**
   * The operation status.
   */
  public void setStatus(int value) {
    pjsua2JNI.OnAudioMediaOpCompletedParam_status_set(swigCPtr, this, value);
  }

  /**
   * The operation status.
   */
  public int getStatus() {
    return pjsua2JNI.OnAudioMediaOpCompletedParam_status_get(swigCPtr, this);
  }

  /**
   * The audio media operation information.<br>
   * <br>
   * App can use <i>AudioMediaHelper</i> to get the AudioMedia instance based on<br>
   * the audio media port id.
   */
  public void setOpParam(AudioMediaOpParam value) {
    pjsua2JNI.OnAudioMediaOpCompletedParam_opParam_set(swigCPtr, this, AudioMediaOpParam.getCPtr(value), value);
  }

  /**
   * The audio media operation information.<br>
   * <br>
   * App can use <i>AudioMediaHelper</i> to get the AudioMedia instance based on<br>
   * the audio media port id.
   */
  public AudioMediaOpParam getOpParam() {
    long cPtr = pjsua2JNI.OnAudioMediaOpCompletedParam_opParam_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AudioMediaOpParam(cPtr, false);
  }

  public OnAudioMediaOpCompletedParam() {
    this(pjsua2JNI.new_OnAudioMediaOpCompletedParam(), true);
  }

}
