/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Parameters for onInstantMessageStatus() account callback.
 */
public class OnInstantMessageStatusParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnInstantMessageStatusParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnInstantMessageStatusParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OnInstantMessageStatusParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnInstantMessageStatusParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Token or a user data that was associated with the pager<br>
   * transmission.
   */
  public void setUserData(long value) {
    pjsua2JNI.OnInstantMessageStatusParam_userData_set(swigCPtr, this, value);
  }

  /**
   * Token or a user data that was associated with the pager<br>
   * transmission.
   */
  public long getUserData() {
    return pjsua2JNI.OnInstantMessageStatusParam_userData_get(swigCPtr, this);
  }

  /**
   * Destination URI.
   */
  public void setToUri(String value) {
    pjsua2JNI.OnInstantMessageStatusParam_toUri_set(swigCPtr, this, value);
  }

  /**
   * Destination URI.
   */
  public String getToUri() {
    return pjsua2JNI.OnInstantMessageStatusParam_toUri_get(swigCPtr, this);
  }

  /**
   * The message body.
   */
  public void setMsgBody(String value) {
    pjsua2JNI.OnInstantMessageStatusParam_msgBody_set(swigCPtr, this, value);
  }

  /**
   * The message body.
   */
  public String getMsgBody() {
    return pjsua2JNI.OnInstantMessageStatusParam_msgBody_get(swigCPtr, this);
  }

  /**
   * The SIP status code of the transaction.
   */
  public void setCode(int value) {
    pjsua2JNI.OnInstantMessageStatusParam_code_set(swigCPtr, this, value);
  }

  /**
   * The SIP status code of the transaction.
   */
  public int getCode() {
    return pjsua2JNI.OnInstantMessageStatusParam_code_get(swigCPtr, this);
  }

  /**
   * The reason phrase of the transaction.
   */
  public void setReason(String value) {
    pjsua2JNI.OnInstantMessageStatusParam_reason_set(swigCPtr, this, value);
  }

  /**
   * The reason phrase of the transaction.
   */
  public String getReason() {
    return pjsua2JNI.OnInstantMessageStatusParam_reason_get(swigCPtr, this);
  }

  /**
   * The incoming response that causes this callback to be called.<br>
   * If the transaction fails because of time out or transport error,<br>
   * the content will be empty.
   */
  public void setRdata(SipRxData value) {
    pjsua2JNI.OnInstantMessageStatusParam_rdata_set(swigCPtr, this, SipRxData.getCPtr(value), value);
  }

  /**
   * The incoming response that causes this callback to be called.<br>
   * If the transaction fails because of time out or transport error,<br>
   * the content will be empty.
   */
  public SipRxData getRdata() {
    long cPtr = pjsua2JNI.OnInstantMessageStatusParam_rdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SipRxData(cPtr, false);
  }

  public OnInstantMessageStatusParam() {
    this(pjsua2JNI.new_OnInstantMessageStatusParam(), true);
  }

}
