/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pj_qos_wmm_prio {
  public final static pj_qos_wmm_prio PJ_QOS_WMM_PRIO_BULK_EFFORT = new pj_qos_wmm_prio("PJ_QOS_WMM_PRIO_BULK_EFFORT");
  public final static pj_qos_wmm_prio PJ_QOS_WMM_PRIO_BULK = new pj_qos_wmm_prio("PJ_QOS_WMM_PRIO_BULK");
  public final static pj_qos_wmm_prio PJ_QOS_WMM_PRIO_VIDEO = new pj_qos_wmm_prio("PJ_QOS_WMM_PRIO_VIDEO");
  public final static pj_qos_wmm_prio PJ_QOS_WMM_PRIO_VOICE = new pj_qos_wmm_prio("PJ_QOS_WMM_PRIO_VOICE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static pj_qos_wmm_prio swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + pj_qos_wmm_prio.class + " with value " + swigValue);
  }

  private pj_qos_wmm_prio(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private pj_qos_wmm_prio(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private pj_qos_wmm_prio(String swigName, pj_qos_wmm_prio swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static pj_qos_wmm_prio[] swigValues = { PJ_QOS_WMM_PRIO_BULK_EFFORT, PJ_QOS_WMM_PRIO_BULK, PJ_QOS_WMM_PRIO_VIDEO, PJ_QOS_WMM_PRIO_VOICE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

