/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pj_ssl_cipher {
  public final static int PJ_TLS_UNKNOWN_CIPHER = -1;
  public final static int PJ_TLS_NULL_WITH_NULL_NULL = 0;
  public final static int PJ_TLS_RSA_WITH_NULL_MD5 = 1;
  public final static int PJ_TLS_RSA_WITH_NULL_SHA = 2;
  public final static int PJ_TLS_RSA_WITH_NULL_SHA256 = 59;
  public final static int PJ_TLS_RSA_WITH_RC4_128_MD5 = 4;
  public final static int PJ_TLS_RSA_WITH_RC4_128_SHA = 5;
  public final static int PJ_TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10;
  public final static int PJ_TLS_RSA_WITH_AES_128_CBC_SHA = 47;
  public final static int PJ_TLS_RSA_WITH_AES_256_CBC_SHA = 53;
  public final static int PJ_TLS_RSA_WITH_AES_128_CBC_SHA256 = 60;
  public final static int PJ_TLS_RSA_WITH_AES_256_CBC_SHA256 = 61;
  public final static int PJ_TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13;
  public final static int PJ_TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16;
  public final static int PJ_TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19;
  public final static int PJ_TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22;
  public final static int PJ_TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48;
  public final static int PJ_TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49;
  public final static int PJ_TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50;
  public final static int PJ_TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51;
  public final static int PJ_TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54;
  public final static int PJ_TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55;
  public final static int PJ_TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56;
  public final static int PJ_TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57;
  public final static int PJ_TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62;
  public final static int PJ_TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63;
  public final static int PJ_TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64;
  public final static int PJ_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103;
  public final static int PJ_TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104;
  public final static int PJ_TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105;
  public final static int PJ_TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106;
  public final static int PJ_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107;
  public final static int PJ_TLS_DH_anon_WITH_RC4_128_MD5 = 24;
  public final static int PJ_TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27;
  public final static int PJ_TLS_DH_anon_WITH_AES_128_CBC_SHA = 52;
  public final static int PJ_TLS_DH_anon_WITH_AES_256_CBC_SHA = 58;
  public final static int PJ_TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108;
  public final static int PJ_TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109;
  public final static int PJ_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196;
  public final static int PJ_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200;
  public final static int PJ_TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163;
  public final static int PJ_TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159;
  public final static int PJ_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195;
  public final static int PJ_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199;
  public final static int PJ_TLS_AES_128_GCM_SHA256 = 4865;
  public final static int PJ_TLS_AES_256_GCM_SHA384 = 4866;
  public final static int PJ_TLS_CHACHA20_POLY1305_SHA256 = 4867;
  public final static int PJ_TLS_RSA_EXPORT_WITH_RC4_40_MD5 = 3;
  public final static int PJ_TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6;
  public final static int PJ_TLS_RSA_WITH_IDEA_CBC_SHA = 7;
  public final static int PJ_TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = 8;
  public final static int PJ_TLS_RSA_WITH_DES_CBC_SHA = 9;
  public final static int PJ_TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11;
  public final static int PJ_TLS_DH_DSS_WITH_DES_CBC_SHA = 12;
  public final static int PJ_TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14;
  public final static int PJ_TLS_DH_RSA_WITH_DES_CBC_SHA = 15;
  public final static int PJ_TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17;
  public final static int PJ_TLS_DHE_DSS_WITH_DES_CBC_SHA = 18;
  public final static int PJ_TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20;
  public final static int PJ_TLS_DHE_RSA_WITH_DES_CBC_SHA = 21;
  public final static int PJ_TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23;
  public final static int PJ_TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25;
  public final static int PJ_TLS_DH_anon_WITH_DES_CBC_SHA = 26;
  public final static int PJ_SSL_FORTEZZA_KEA_WITH_NULL_SHA = 28;
  public final static int PJ_SSL_FORTEZZA_KEA_WITH_FORTEZZA_CBC_SHA = 29;
  public final static int PJ_SSL_FORTEZZA_KEA_WITH_RC4_128_SHA = 30;
  public final static int PJ_SSL_CK_RC4_128_WITH_MD5 = 65664;
  public final static int PJ_SSL_CK_RC4_128_EXPORT40_WITH_MD5 = 131200;
  public final static int PJ_SSL_CK_RC2_128_CBC_WITH_MD5 = 196736;
  public final static int PJ_SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5 = 262272;
  public final static int PJ_SSL_CK_IDEA_128_CBC_WITH_MD5 = 327808;
  public final static int PJ_SSL_CK_DES_64_CBC_WITH_MD5 = 393280;
  public final static int PJ_SSL_CK_DES_192_EDE3_CBC_WITH_MD5 = 458944;
}

