/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_file_writer_option {
  public final static int PJMEDIA_FILE_WRITE_PCM = 0;
  public final static int PJMEDIA_FILE_WRITE_ALAW = 1;
  public final static int PJMEDIA_FILE_WRITE_ULAW = 2;
}

