/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_aud_dev_route {
  public final static int PJMEDIA_AUD_DEV_ROUTE_DEFAULT = 0;
  public final static int PJMEDIA_AUD_DEV_ROUTE_LOUDSPEAKER = 1;
  public final static int PJMEDIA_AUD_DEV_ROUTE_EARPIECE = 2;
  public final static int PJMEDIA_AUD_DEV_ROUTE_BLUETOOTH = 4;
  public final static int PJMEDIA_AUD_DEV_ROUTE_CUSTOM = 128;
}

