/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_vid_stream_rc_method {
  public final static int PJMEDIA_VID_STREAM_RC_NONE = 0;
  public final static int PJMEDIA_VID_STREAM_RC_SIMPLE_BLOCKING = 1;
}

