/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_srtp_crypto_option {
  public final static int PJMEDIA_SRTP_NO_ENCRYPTION = 1;
  public final static int PJMEDIA_SRTP_NO_AUTHENTICATION = 2;
}

