/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsip_cred_data_type {
  public final static int PJSIP_CRED_DATA_PLAIN_PASSWD = 0;
  public final static int PJSIP_CRED_DATA_DIGEST = 1;
  public final static int PJSIP_CRED_DATA_EXT_AKA = 16;
}

