/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsip_transport_flags_e {
  public final static int PJSIP_TRANSPORT_RELIABLE = 1;
  public final static int PJSIP_TRANSPORT_SECURE = 2;
  public final static int PJSIP_TRANSPORT_DATAGRAM = 4;
}

