/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsip_ssl_method {
  public final static int PJSIP_SSL_UNSPECIFIED_METHOD = 0;
  public final static int PJSIP_SSLV2_METHOD = 20;
  public final static int PJSIP_SSLV3_METHOD = 30;
  public final static int PJSIP_TLSV1_METHOD = 31;
  public final static int PJSIP_TLSV1_1_METHOD = 32;
  public final static int PJSIP_TLSV1_2_METHOD = 33;
  public final static int PJSIP_TLSV1_3_METHOD = 34;
  public final static int PJSIP_SSLV23_METHOD = 23;
}

