/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsip_dialog_cap_status {
  public final static int PJSIP_DIALOG_CAP_UNSUPPORTED = 0;
  public final static int PJSIP_DIALOG_CAP_SUPPORTED = 1;
  public final static int PJSIP_DIALOG_CAP_UNKNOWN = 2;
}

