/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_med_tp_st {
  public final static int PJSUA_MED_TP_NULL = 0;
  public final static int PJSUA_MED_TP_CREATING = PJSUA_MED_TP_NULL + 1;
  public final static int PJSUA_MED_TP_IDLE = PJSUA_MED_TP_CREATING + 1;
  public final static int PJSUA_MED_TP_INIT = PJSUA_MED_TP_IDLE + 1;
  public final static int PJSUA_MED_TP_RUNNING = PJSUA_MED_TP_INIT + 1;
  public final static int PJSUA_MED_TP_DISABLED = PJSUA_MED_TP_RUNNING + 1;
}

