/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_destroy_flag {
  public final static int PJSUA_DESTROY_NO_RX_MSG = 1;
  public final static int PJSUA_DESTROY_NO_TX_MSG = 2;
  public final static int PJSUA_DESTROY_NO_NETWORK = PJSUA_DESTROY_NO_RX_MSG|PJSUA_DESTROY_NO_TX_MSG;
}

