/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_snd_dev_id {
  public final static int PJSUA_SND_DEFAULT_CAPTURE_DEV = -1;
  public final static int PJSUA_SND_DEFAULT_PLAYBACK_DEV = -2;
  public final static int PJSUA_SND_NO_DEV = -3;
  public final static int PJSUA_SND_NULL_DEV = -99;
}

