/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_sip_siprec_use {
  public final static int PJSUA_SIP_SIPREC_INACTIVE = 0;
  public final static int PJSUA_SIP_SIPREC_OPTIONAL = PJSUA_SIP_SIPREC_INACTIVE + 1;
  public final static int PJSUA_SIP_SIPREC_MANDATORY = PJSUA_SIP_SIPREC_OPTIONAL + 1;
}

