/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjsua_ip_change_op {
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_NULL = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_NULL");
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_RESTART_LIS = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_RESTART_LIS");
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_ACC_SHUTDOWN_TP = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_ACC_SHUTDOWN_TP");
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_ACC_UPDATE_CONTACT = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_ACC_UPDATE_CONTACT");
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_ACC_HANGUP_CALLS = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_ACC_HANGUP_CALLS");
  public final static pjsua_ip_change_op PJSUA_IP_CHANGE_OP_ACC_REINVITE_CALLS = new pjsua_ip_change_op("PJSUA_IP_CHANGE_OP_ACC_REINVITE_CALLS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static pjsua_ip_change_op swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + pjsua_ip_change_op.class + " with value " + swigValue);
  }

  private pjsua_ip_change_op(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private pjsua_ip_change_op(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private pjsua_ip_change_op(String swigName, pjsua_ip_change_op swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static pjsua_ip_change_op[] swigValues = { PJSUA_IP_CHANGE_OP_NULL, PJSUA_IP_CHANGE_OP_RESTART_LIS, PJSUA_IP_CHANGE_OP_ACC_SHUTDOWN_TP, PJSUA_IP_CHANGE_OP_ACC_UPDATE_CONTACT, PJSUA_IP_CHANGE_OP_ACC_HANGUP_CALLS, PJSUA_IP_CHANGE_OP_ACC_REINVITE_CALLS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

