/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class SWIGTYPE_p_pjmedia_vid_dev_hwnd_type {
  private transient long swigCPtr;

  protected SWIGTYPE_p_pjmedia_vid_dev_hwnd_type(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_pjmedia_vid_dev_hwnd_type() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_pjmedia_vid_dev_hwnd_type obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

