/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * This structure describes video window info.
 */
public class VideoWindowInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoWindowInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoWindowInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VideoWindowInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoWindowInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Flag to indicate whether this window is a native window,<br>
   * such as created by built-in preview device. If this field is<br>
   * true, only the video window handle field of this<br>
   * structure is valid.
   */
  public void setIsNative(boolean value) {
    pjsua2JNI.VideoWindowInfo_isNative_set(swigCPtr, this, value);
  }

  /**
   * Flag to indicate whether this window is a native window,<br>
   * such as created by built-in preview device. If this field is<br>
   * true, only the video window handle field of this<br>
   * structure is valid.
   */
  public boolean getIsNative() {
    return pjsua2JNI.VideoWindowInfo_isNative_get(swigCPtr, this);
  }

  /**
   * Video window handle.
   */
  public void setWinHandle(VideoWindowHandle value) {
    pjsua2JNI.VideoWindowInfo_winHandle_set(swigCPtr, this, VideoWindowHandle.getCPtr(value), value);
  }

  /**
   * Video window handle.
   */
  public VideoWindowHandle getWinHandle() {
    long cPtr = pjsua2JNI.VideoWindowInfo_winHandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoWindowHandle(cPtr, false);
  }

  /**
   * Renderer device ID.
   */
  public void setRenderDeviceId(int value) {
    pjsua2JNI.VideoWindowInfo_renderDeviceId_set(swigCPtr, this, value);
  }

  /**
   * Renderer device ID.
   */
  public int getRenderDeviceId() {
    return pjsua2JNI.VideoWindowInfo_renderDeviceId_get(swigCPtr, this);
  }

  /**
   * Window show status. The window is hidden if false.
   */
  public void setShow(boolean value) {
    pjsua2JNI.VideoWindowInfo_show_set(swigCPtr, this, value);
  }

  /**
   * Window show status. The window is hidden if false.
   */
  public boolean getShow() {
    return pjsua2JNI.VideoWindowInfo_show_get(swigCPtr, this);
  }

  /**
   * Window position.
   */
  public void setPos(MediaCoordinate value) {
    pjsua2JNI.VideoWindowInfo_pos_set(swigCPtr, this, MediaCoordinate.getCPtr(value), value);
  }

  /**
   * Window position.
   */
  public MediaCoordinate getPos() {
    long cPtr = pjsua2JNI.VideoWindowInfo_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MediaCoordinate(cPtr, false);
  }

  /**
   * Window size.
   */
  public void setSize(MediaSize value) {
    pjsua2JNI.VideoWindowInfo_size_set(swigCPtr, this, MediaSize.getCPtr(value), value);
  }

  /**
   * Window size.
   */
  public MediaSize getSize() {
    long cPtr = pjsua2JNI.VideoWindowInfo_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MediaSize(cPtr, false);
  }

  public VideoWindowInfo() {
    this(pjsua2JNI.new_VideoWindowInfo(), true);
  }

}
