/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Video AVI Player.
 */
public class VideoPlayer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoPlayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoPlayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VideoPlayer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoPlayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Constructor.
   */
  public VideoPlayer() {
    this(pjsua2JNI.new_VideoPlayer(), true);
  }

  /**
   * Create an avi file player, and automatically add this player to<br>
   * the audio/video conference bridge. The player will create a virtual<br>
   * video device and audio/video media port based on the streams contained<br>
   * in the file.<br>
   * The maximum number of stream is limited to PJSUA_MAX_AVI_NUM_STREAMS<br>
   * and the video stream is limited to one stream.<br>
   * <br>
   * 
   */
  public void createVideoPlayer(String file_name) throws java.lang.Exception {
    pjsua2JNI.VideoPlayer_createVideoPlayer(swigCPtr, this, file_name);
  }

  /**
   * Enumerate all audio media port.<br>
   * <br>
   * @return The list of audio media port.
   */
  public AudioMediaVector2 mediaEnumPorts() throws java.lang.Exception {
    return new AudioMediaVector2(pjsua2JNI.VideoPlayer_mediaEnumPorts(swigCPtr, this), true);
  }

  /**
   * Enumerate all video media port.<br>
   * <br>
   * @return The list of video media port.
   */
  public VideoMediaVector mediaEnumVidPorts() throws java.lang.Exception {
    return new VideoMediaVector(pjsua2JNI.VideoPlayer_mediaEnumVidPorts(swigCPtr, this), true);
  }

  /**
   * Get the video device index of the avi player. Application can use this<br>
   * index as the video source/capture device.<br>
   * <br>
   * @return The video device index.
   */
  public int getVideoDevId() throws java.lang.Exception {
    return pjsua2JNI.VideoPlayer_getVideoDevId(swigCPtr, this);
  }

}
