/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * This structure describes an video media's update operation info.
 */
public class VideoMediaUpdateInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoMediaUpdateInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoMediaUpdateInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VideoMediaUpdateInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoMediaUpdateInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  The media port id.            
   */
  public void setMediaId(long value) {
    pjsua2JNI.VideoMediaUpdateInfo_mediaId_set(swigCPtr, this, value);
  }

  /**
   *  The media port id.            
   */
  public long getMediaId() {
    return pjsua2JNI.VideoMediaUpdateInfo_mediaId_get(swigCPtr, this);
  }

  public VideoMediaUpdateInfo() {
    this(pjsua2JNI.new_VideoMediaUpdateInfo(), true);
  }

}
